Repository FRONTENDBOOTCAMP-11th/febc11-vanilla-team2, pull requests merged in 2024-10, with the labels that each got.

#23 💄 style : global-styles-css-reset 추가
  src/assets/css/base/reset.css
Labels: enhancement, Medium

#26 Feature/19 login page
  .vscode/settings.json
  index.html
  package-lock.json
  package.json
  src/assets/icons/check.svg
  src/assets/icons/eye-off.svg
  src/assets/images/login.svg
  src/pages/login/login.css
  src/pages/login/login.html
  src/pages/login/signup.html
Labels: enhancement, High

#27 Feature/16 write
  .vscode/settings.json
  src/assets/icons/keyboard.svg
  src/pages/write/write.css
  src/pages/write/write.html
Labels: enhancement, High

#29 Feature/17 my drawer page
  package.json
  src/assets/icons/mydrawer-off.svg
  src/assets/icons/mydrawer-on.svg
  src/assets/icons/write-off.svg
  src/assets/icons/write-on.svg
  src/assets/images/book-1.svg
  src/assets/images/book-2.svg
  src/assets/images/book-3.svg
  src/pages/myDrawer/myDrawer.css
  src/pages/myDrawer/myDrawer.html
Labels: enhancement, High

#30 Feature/20 detail page
  package.json
  src/assets/icons/by.svg
  src/assets/icons/detail-btn.svg
  src/assets/icons/message.svg
  src/assets/icons/share.svg
  src/assets/icons/submit-btn.svg
  src/assets/icons/subscribe.svg
  src/pages/detailPage/detailPage.css
  src/pages/detailPage/detailPage.html
  src/pages/detailPage/detailPage.js
  src/pages/login/login.css
  src/pages/login/signup.html
Labels: enhancement, High

#33 Feature/21 author
  src/assets/icons/subscribe-off.svg
  src/assets/icons/subscribe-on.svg
  src/pages/author/author.css
  src/pages/author/author.html
Labels: enhancement, High

#36 Feature/18 search page
  src/assets/icons/clear-button.svg
  src/assets/icons/delete.svg
  src/assets/images/result-article-1.svg
  src/assets/images/result-dismatch.svg
  src/assets/images/search-article-1.svg
  src/pages/myDrawer/myDrawer.css
  src/pages/search/search.css
  src/pages/search/search.html
  src/pages/search/search.js
Labels: enhancement, High

#58 [FEATURE] 발견 페이지 기능 구현
  src/pages/search/search.css
  src/pages/search/search.html
  src/pages/search/search.js
Labels: enhancement, High

#59 Feature/50 component
  api/bruno-sample/brunch/02-게시판/게시판 목록.bru
  src/components/footer.css
  src/components/footer.html
  src/components/footer.js
  src/components/header-logged-in.html
  src/components/header-logged-out.html
  src/components/header.css
  src/components/header.js
  src/components/wrapper.css
  src/pages/author/author.css
  src/pages/author/author.html
  src/pages/detailPage/detailPage.css
  src/pages/detailPage/detailPage.html
  src/pages/main/main.css
  src/pages/main/main.html
  src/pages/myDrawer/myDrawer.css
  src/pages/myDrawer/myDrawer.html
  src/pages/search/search.css
  src/pages/search/search.html
  src/pages/write/write.html
Labels: enhancement, High

#81 🐞 bugfix : 내 서랍 - 관심 글 상세페이지 이동 시 문제 해결
  src/pages/myDrawer/myDrawer.css
  src/pages/myDrawer/myDrawer.js
Labels: bug, High

#88 [BUGFIX] 파라미터값 _id -> id로 변경, 기본이미지, 기본직업 설정
  src/pages/author/author.html
  src/pages/author/author.js
Labels: bug

#89 Bugfix/87 search page bugfix
  src/pages/search/search.css
  src/pages/search/search.js
Labels: bug, High

#96 Bugfix/92 search my drawer bug
  src/pages/detailPage/detailPage.js
  src/pages/myDrawer/myDrawer.css
  src/pages/myDrawer/myDrawer.js
  src/pages/search/search.js
Labels: bug, High
